// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore `.open-next/worker.js` is generated by `pnpm run worker:build`.
import generatedWorker from "./.open-next/worker.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore `.open-next/worker.js` is generated by `pnpm run worker:build`.
export { DOQueueHandler } from "./.open-next/worker.js";

interface AppWorkerEnv extends CloudflareEnv {
  APP_D1: D1Database;
}

function withAppBindings(env: CloudflareEnv): AppWorkerEnv {
  const database = env.NEXT_TAG_CACHE_D1;

  if (!database) {
    throw new Error("Missing required Cloudflare D1 binding: NEXT_TAG_CACHE_D1");
  }

  return {
    ...env,
    APP_D1: database,
  };
}

const worker = {
  async fetch(request, env, ctx) {
    return generatedWorker.fetch(request, withAppBindings(env), ctx);
  },
} satisfies ExportedHandler<CloudflareEnv>;

export default worker;
