// Extracted embassy mapping for new application onboarding.
export const EMBASSY_DATA: Record<string, Record<string, string[]>> = {
  "United States": {
    "Bangladesh": ["U.S. Embassy Dhaka"],
    "India": ["U.S. Embassy New Delhi", "U.S. Consulate Mumbai", "U.S. Consulate Chennai", "U.S. Consulate Kolkata", "U.S. Consulate Hyderabad"],
    "Pakistan": ["U.S. Embassy Islamabad", "U.S. Consulate Karachi", "U.S. Consulate Lahore", "U.S. Consulate Peshawar"],
    "Nepal": ["U.S. Embassy Kathmandu"],
    "Sri Lanka": ["U.S. Embassy Colombo"],
    "Nigeria": ["U.S. Embassy Abuja", "U.S. Consulate Lagos"],
    "Ghana": ["U.S. Embassy Accra"],
    "Kenya": ["U.S. Embassy Nairobi"],
    "South Africa": ["U.S. Embassy Pretoria", "U.S. Consulate Cape Town", "U.S. Consulate Johannesburg"],
    "Egypt": ["U.S. Embassy Cairo"],
    "Morocco": ["U.S. Embassy Rabat", "U.S. Consulate Casablanca"],
    "China": ["U.S. Embassy Beijing", "U.S. Consulate Shanghai", "U.S. Consulate Guangzhou", "U.S. Consulate Chengdu", "U.S. Consulate Shenyang"],
    "Japan": ["U.S. Embassy Tokyo", "U.S. Consulate Osaka-Kobe", "U.S. Consulate Naha", "U.S. Consulate Sapporo", "U.S. Consulate Fukuoka"],
    "South Korea": ["U.S. Embassy Seoul", "U.S. Consulate Busan"],
    "Philippines": ["U.S. Embassy Manila"],
    "Vietnam": ["U.S. Embassy Hanoi", "U.S. Consulate Ho Chi Minh City"],
    "Thailand": ["U.S. Embassy Bangkok", "U.S. Consulate Chiang Mai"],
    "Indonesia": ["U.S. Embassy Jakarta", "U.S. Consulate Surabaya"],
    "Malaysia": ["U.S. Embassy Kuala Lumpur"],
    "Singapore": ["U.S. Embassy Singapore"],
    "Mexico": ["U.S. Embassy Mexico City", "U.S. Consulate Guadalajara", "U.S. Consulate Monterrey", "U.S. Consulate Tijuana", "U.S. Consulate Juarez", "U.S. Consulate Merida"],
    "Brazil": ["U.S. Embassy Brasilia", "U.S. Consulate Rio de Janeiro", "U.S. Consulate Sao Paulo", "U.S. Consulate Recife", "U.S. Consulate Porto Alegre"],
    "Colombia": ["U.S. Embassy Bogota"],
    "Peru": ["U.S. Embassy Lima"],
    "Argentina": ["U.S. Embassy Buenos Aires"],
    "Turkey": ["U.S. Embassy Ankara", "U.S. Consulate Istanbul", "U.S. Consulate Adana"],
    "Germany": ["U.S. Embassy Berlin", "U.S. Consulate Frankfurt", "U.S. Consulate Munich", "U.S. Consulate Hamburg"],
    "France": ["U.S. Embassy Paris", "U.S. Consulate Bordeaux", "U.S. Consulate Lyon", "U.S. Consulate Marseille"],
    "United Kingdom": ["U.S. Embassy London", "U.S. Consulate Belfast", "U.S. Consulate Edinburgh"],
    "Saudi Arabia": ["U.S. Embassy Riyadh", "U.S. Consulate Jeddah", "U.S. Consulate Dhahran"],
    "United Arab Emirates": ["U.S. Embassy Abu Dhabi", "U.S. Consulate Dubai"],
    "Israel": ["U.S. Embassy Jerusalem", "U.S. Branch Office Tel Aviv"],
    "Ethiopia": ["U.S. Embassy Addis Ababa"],
    "Tanzania": ["U.S. Embassy Dar es Salaam"],
    "Uganda": ["U.S. Embassy Kampala"],
    "Jordan": ["U.S. Embassy Amman"],
    "Lebanon": ["U.S. Embassy Beirut"],
    "Kazakhstan": ["U.S. Embassy Nur-Sultan"],
    "Uzbekistan": ["U.S. Embassy Tashkent"],
    "Azerbaijan": ["U.S. Embassy Baku"],
    "Georgia": ["U.S. Embassy Tbilisi"],
    "Canada": ["U.S. Embassy Ottawa", "U.S. Consulate Calgary", "U.S. Consulate Halifax", "U.S. Consulate Montreal", "U.S. Consulate Toronto", "U.S. Consulate Vancouver"],
    "Australia": ["U.S. Embassy Canberra", "U.S. Consulate Melbourne", "U.S. Consulate Perth", "U.S. Consulate Sydney"],
    "New Zealand": ["U.S. Embassy Wellington"],
    "Ukraine": ["U.S. Embassy Kyiv"],
    "Russia": ["U.S. Embassy Moscow", "U.S. Consulate Vladivostok", "U.S. Consulate Yekaterinburg"],
    "Iran": ["No U.S. Embassy in Iran — apply via Swiss Embassy Tehran (Swiss Protecting Power)"],
  },
  "United Kingdom": {
    "Bangladesh": ["British High Commission Dhaka"],
    "India": ["British High Commission New Delhi", "British Deputy High Commission Mumbai", "British Deputy High Commission Chennai", "British Deputy High Commission Kolkata", "British Deputy High Commission Ahmedabad", "British Deputy High Commission Hyderabad"],
    "Pakistan": ["British High Commission Islamabad", "British Deputy High Commission Karachi", "British Deputy High Commission Lahore"],
    "Nepal": ["British Embassy Kathmandu"],
    "Sri Lanka": ["British High Commission Colombo"],
    "Nigeria": ["British High Commission Abuja", "British Deputy High Commission Lagos"],
    "Ghana": ["British High Commission Accra"],
    "Kenya": ["British High Commission Nairobi"],
    "South Africa": ["British High Commission Pretoria", "British Consulate Cape Town"],
    "Egypt": ["British Embassy Cairo"],
    "Morocco": ["British Embassy Rabat", "British Consulate Casablanca"],
    "China": ["British Embassy Beijing", "British Consulate-General Shanghai", "British Consulate-General Guangzhou", "British Consulate-General Chongqing"],
    "Japan": ["British Embassy Tokyo"],
    "South Korea": ["British Embassy Seoul"],
    "Philippines": ["British Embassy Manila"],
    "Vietnam": ["British Embassy Hanoi", "British Consulate-General Ho Chi Minh City"],
    "Thailand": ["British Embassy Bangkok"],
    "Indonesia": ["British Embassy Jakarta"],
    "Malaysia": ["British High Commission Kuala Lumpur"],
    "Singapore": ["British High Commission Singapore"],
    "Mexico": ["British Embassy Mexico City"],
    "Brazil": ["British Embassy Brasilia", "British Consulate-General Rio de Janeiro", "British Consulate-General Sao Paulo"],
    "Colombia": ["British Embassy Bogota"],
    "Turkey": ["British Embassy Ankara", "British Consulate-General Istanbul"],
    "Iran": ["British Embassy Tehran"],
    "Germany": ["British Embassy Berlin", "British Consulate-General Dusseldorf", "British Consulate-General Munich"],
    "France": ["British Embassy Paris", "British Consulate-General Bordeaux", "British Consulate-General Marseille"],
    "United States": ["British Embassy Washington D.C.", "British Consulate-General Atlanta", "British Consulate-General Boston", "British Consulate-General Chicago", "British Consulate-General Houston", "British Consulate-General Los Angeles", "British Consulate-General Miami", "British Consulate-General New York", "British Consulate-General San Francisco"],
    "Canada": ["British High Commission Ottawa", "British Consulate-General Montreal", "British Consulate-General Toronto", "British Consulate-General Vancouver"],
    "Australia": ["British High Commission Canberra", "British Consulate-General Melbourne", "British Consulate-General Sydney"],
    "Saudi Arabia": ["British Embassy Riyadh", "British Consulate-General Jeddah", "British Consulate-General Al Khobar"],
    "United Arab Emirates": ["British Embassy Abu Dhabi", "British Consulate-General Dubai"],
    "Ukraine": ["British Embassy Kyiv"],
    "Russia": ["British Embassy Moscow", "British Consulate-General Yekaterinburg"],
    "Jordan": ["British Embassy Amman"],
    "Ethiopia": ["British Embassy Addis Ababa"],
    "Tanzania": ["British High Commission Dar es Salaam"],
    "Uganda": ["British High Commission Kampala"],
    "Zimbabwe": ["British Embassy Harare"],
    "Senegal": ["British Embassy Dakar"],
    "Kazakhstan": ["British Embassy Nur-Sultan"],
  },
  "Canada": {
    "Bangladesh": ["Canadian High Commission Dhaka"],
    "India": ["High Commission of Canada New Delhi", "Consulate General of Canada Mumbai", "Consulate General of Canada Chandigarh"],
    "Pakistan": ["Canadian High Commission Islamabad", "Canadian Consulate Karachi"],
    "Nepal": ["Canadian Embassy Kathmandu"],
    "Sri Lanka": ["Canadian High Commission Colombo"],
    "Nigeria": ["Canadian High Commission Abuja", "Canadian Consulate Lagos"],
    "Ghana": ["Canadian High Commission Accra"],
    "Kenya": ["Canadian High Commission Nairobi"],
    "South Africa": ["Canadian High Commission Pretoria"],
    "Egypt": ["Canadian Embassy Cairo"],
    "Morocco": ["Canadian Embassy Rabat"],
    "China": ["Canadian Embassy Beijing", "Canadian Consulate-General Shanghai", "Canadian Consulate-General Guangzhou", "Canadian Consulate-General Chongqing"],
    "Japan": ["Canadian Embassy Tokyo"],
    "South Korea": ["Canadian Embassy Seoul"],
    "Philippines": ["Canadian Embassy Manila"],
    "Vietnam": ["Canadian Embassy Hanoi", "Canadian Consulate-General Ho Chi Minh City"],
    "Thailand": ["Canadian Embassy Bangkok"],
    "Indonesia": ["Canadian Embassy Jakarta"],
    "Malaysia": ["Canadian High Commission Kuala Lumpur"],
    "Singapore": ["Canadian High Commission Singapore"],
    "Mexico": ["Canadian Embassy Mexico City", "Canadian Consulate Monterrey", "Canadian Consulate Guadalajara", "Canadian Consulate Cancun"],
    "Brazil": ["Canadian Embassy Brasilia", "Canadian Consulate-General Sao Paulo"],
    "Colombia": ["Canadian Embassy Bogota"],
    "Turkey": ["Canadian Embassy Ankara", "Canadian Consulate-General Istanbul"],
    "United States": ["Canadian Embassy Washington D.C.", "Canadian Consulate-General New York", "Canadian Consulate-General Los Angeles", "Canadian Consulate-General Seattle", "Canadian Consulate-General Detroit", "Canadian Consulate-General Chicago", "Canadian Consulate-General Atlanta", "Canadian Consulate-General Denver", "Canadian Consulate-General Miami"],
    "United Kingdom": ["Canadian High Commission London"],
    "Australia": ["Canadian High Commission Canberra", "Canadian Consulate-General Sydney"],
    "Saudi Arabia": ["Canadian Embassy Riyadh"],
    "United Arab Emirates": ["Canadian Embassy Abu Dhabi", "Canadian Consulate Dubai"],
    "Ethiopia": ["Canadian Embassy Addis Ababa"],
    "Ukraine": ["Canadian Embassy Kyiv"],
    "Kazakhstan": ["Canadian Embassy Nur-Sultan"],
  },
  "Australia": {
    "Bangladesh": ["Australian High Commission Dhaka"],
    "India": ["Australian High Commission New Delhi", "Australian Consulate-General Mumbai", "Australian Consulate-General Chennai", "Australian Consulate-General Kolkata"],
    "Pakistan": ["Australian High Commission Islamabad", "Australian Consulate-General Karachi"],
    "Nepal": ["Australian Embassy Kathmandu"],
    "Sri Lanka": ["Australian High Commission Colombo"],
    "Nigeria": ["Australian High Commission Abuja"],
    "Ghana": ["Australian High Commission Accra"],
    "Kenya": ["Australian High Commission Nairobi"],
    "South Africa": ["Australian High Commission Pretoria"],
    "Egypt": ["Australian Embassy Cairo"],
    "Morocco": ["Australian Embassy Rabat"],
    "China": ["Australian Embassy Beijing", "Australian Consulate-General Shanghai", "Australian Consulate-General Guangzhou", "Australian Consulate-General Chengdu"],
    "Japan": ["Australian Embassy Tokyo", "Australian Consulate-General Osaka"],
    "South Korea": ["Australian Embassy Seoul"],
    "Philippines": ["Australian Embassy Manila", "Australian Consulate-General Cebu"],
    "Vietnam": ["Australian Embassy Hanoi", "Australian Consulate-General Ho Chi Minh City"],
    "Thailand": ["Australian Embassy Bangkok"],
    "Indonesia": ["Australian Embassy Jakarta", "Australian Consulate-General Bali", "Australian Consulate-General Surabaya"],
    "Malaysia": ["Australian High Commission Kuala Lumpur"],
    "Singapore": ["Australian High Commission Singapore"],
    "Mexico": ["Australian Embassy Mexico City"],
    "Brazil": ["Australian Embassy Brasilia", "Australian Consulate-General Sao Paulo"],
    "United States": ["Australian Embassy Washington D.C.", "Australian Consulate-General Los Angeles", "Australian Consulate-General New York", "Australian Consulate-General San Francisco", "Australian Consulate-General Houston", "Australian Consulate-General Chicago"],
    "United Kingdom": ["Australian High Commission London"],
    "Canada": ["Australian High Commission Canberra", "Australian Consulate-General Toronto", "Australian Consulate-General Vancouver"],
    "Germany": ["Australian Embassy Berlin", "Australian Consulate-General Frankfurt"],
    "France": ["Australian Embassy Paris"],
    "Saudi Arabia": ["Australian Embassy Riyadh"],
    "United Arab Emirates": ["Australian Embassy Abu Dhabi", "Australian Consulate-General Dubai"],
    "Turkey": ["Australian Embassy Ankara", "Australian Consulate-General Istanbul"],
    "Iran": ["Australian Embassy Tehran"],
    "Ethiopia": ["Australian Embassy Addis Ababa"],
    "Ukraine": ["Australian Embassy Kyiv"],
  },
  "Germany": {
    "Bangladesh": ["German Embassy Dhaka"],
    "India": ["German Embassy New Delhi", "German Consulate-General Mumbai", "German Consulate-General Chennai", "German Consulate-General Kolkata", "German Consulate-General Bangalore"],
    "Pakistan": ["German Embassy Islamabad", "German Consulate Karachi"],
    "Nepal": ["German Embassy Kathmandu"],
    "Sri Lanka": ["German Embassy Colombo"],
    "Nigeria": ["German Embassy Abuja", "German Consulate-General Lagos"],
    "Ghana": ["German Embassy Accra"],
    "Kenya": ["German Embassy Nairobi"],
    "South Africa": ["German Embassy Pretoria", "German Consulate-General Cape Town", "German Consulate-General Johannesburg"],
    "Egypt": ["German Embassy Cairo"],
    "Morocco": ["German Embassy Rabat", "German Consulate-General Casablanca"],
    "China": ["German Embassy Beijing", "German Consulate-General Shanghai", "German Consulate-General Guangzhou", "German Consulate-General Chengdu", "German Consulate-General Shenyang"],
    "Japan": ["German Embassy Tokyo", "German Consulate-General Osaka"],
    "South Korea": ["German Embassy Seoul"],
    "Philippines": ["German Embassy Manila"],
    "Vietnam": ["German Embassy Hanoi", "German Consulate-General Ho Chi Minh City"],
    "Thailand": ["German Embassy Bangkok"],
    "Indonesia": ["German Embassy Jakarta"],
    "Malaysia": ["German Embassy Kuala Lumpur"],
    "Singapore": ["German Embassy Singapore"],
    "Turkey": ["German Embassy Ankara", "German Consulate-General Istanbul", "German Consulate-General Izmir"],
    "Iran": ["German Embassy Tehran"],
    "United States": ["German Embassy Washington D.C.", "German Consulate-General New York", "German Consulate-General Los Angeles", "German Consulate-General San Francisco", "German Consulate-General Chicago", "German Consulate-General Houston", "German Consulate-General Miami"],
    "United Kingdom": ["German Embassy London"],
    "Canada": ["German Embassy Ottawa", "German Consulate-General Montreal", "German Consulate-General Toronto", "German Consulate-General Vancouver"],
    "Australia": ["German Embassy Canberra", "German Consulate-General Sydney", "German Consulate-General Melbourne"],
    "Brazil": ["German Embassy Brasilia", "German Consulate-General Sao Paulo", "German Consulate-General Rio de Janeiro", "German Consulate-General Porto Alegre"],
    "Mexico": ["German Embassy Mexico City"],
    "Saudi Arabia": ["German Embassy Riyadh", "German Consulate-General Jeddah"],
    "United Arab Emirates": ["German Embassy Abu Dhabi", "German Consulate-General Dubai"],
    "Ukraine": ["German Embassy Kyiv"],
    "Russia": ["German Embassy Moscow", "German Consulate-General St. Petersburg", "German Consulate-General Novosibirsk", "German Consulate-General Yekaterinburg"],
    "Ethiopia": ["German Embassy Addis Ababa"],
    "Jordan": ["German Embassy Amman"],
    "Lebanon": ["German Embassy Beirut"],
    "Kazakhstan": ["German Embassy Nur-Sultan"],
    "Uzbekistan": ["German Embassy Tashkent"],
    "Azerbaijan": ["German Embassy Baku"],
    "Georgia": ["German Embassy Tbilisi"],
  },
  "France": {
    "Bangladesh": ["French Embassy Dhaka"],
    "India": ["French Embassy New Delhi", "French Consulate-General Mumbai", "French Consulate-General Chennai", "French Consulate-General Kolkata", "French Consulate-General Pondicherry", "French Consulate-General Bangalore"],
    "Pakistan": ["French Embassy Islamabad", "French Consulate Karachi", "French Consulate Lahore"],
    "Nepal": ["French Embassy Kathmandu"],
    "Sri Lanka": ["French Embassy Colombo"],
    "Nigeria": ["French Embassy Abuja", "French Consulate-General Lagos"],
    "Ghana": ["French Embassy Accra"],
    "Kenya": ["French Embassy Nairobi"],
    "South Africa": ["French Embassy Pretoria", "French Consulate-General Johannesburg"],
    "Egypt": ["French Embassy Cairo", "French Consulate Alexandria"],
    "Morocco": ["French Embassy Rabat", "French Consulate-General Casablanca", "French Consulate Fez", "French Consulate Marrakech", "French Consulate Agadir"],
    "China": ["French Embassy Beijing", "French Consulate-General Shanghai", "French Consulate-General Guangzhou", "French Consulate-General Chengdu", "French Consulate-General Wuhan", "French Consulate-General Shenyang"],
    "Japan": ["French Embassy Tokyo", "French Consulate-General Osaka"],
    "South Korea": ["French Embassy Seoul"],
    "Philippines": ["French Embassy Manila"],
    "Vietnam": ["French Embassy Hanoi", "French Consulate-General Ho Chi Minh City"],
    "Thailand": ["French Embassy Bangkok"],
    "Indonesia": ["French Embassy Jakarta"],
    "Malaysia": ["French Embassy Kuala Lumpur"],
    "Singapore": ["French Embassy Singapore"],
    "Turkey": ["French Embassy Ankara", "French Consulate-General Istanbul"],
    "United States": ["French Embassy Washington D.C.", "French Consulate-General New York", "French Consulate-General Los Angeles", "French Consulate-General Chicago", "French Consulate-General Houston", "French Consulate-General Miami", "French Consulate-General Atlanta", "French Consulate-General Boston"],
    "United Kingdom": ["French Embassy London"],
    "Canada": ["French Embassy Ottawa", "French Consulate-General Montreal", "French Consulate-General Toronto", "French Consulate-General Vancouver", "French Consulate-General Quebec City"],
    "Australia": ["French Embassy Canberra", "French Consulate-General Sydney", "French Consulate-General Melbourne"],
    "Brazil": ["French Embassy Brasilia", "French Consulate-General Sao Paulo", "French Consulate-General Rio de Janeiro"],
    "Saudi Arabia": ["French Embassy Riyadh", "French Consulate-General Jeddah"],
    "United Arab Emirates": ["French Embassy Abu Dhabi", "French Consulate-General Dubai"],
    "Algeria": ["French Embassy Algiers", "French Consulate-General Oran", "French Consulate-General Annaba"],
    "Tunisia": ["French Embassy Tunis"],
    "Senegal": ["French Embassy Dakar"],
    "Iran": ["French Embassy Tehran"],
    "Ukraine": ["French Embassy Kyiv"],
    "Russia": ["French Embassy Moscow", "French Consulate-General St. Petersburg"],
    "Jordan": ["French Embassy Amman"],
    "Lebanon": ["French Embassy Beirut"],
  },
  "Netherlands": {
    "Bangladesh": ["Netherlands Embassy Dhaka"],
    "India": ["Netherlands Embassy New Delhi", "Netherlands Consulate-General Mumbai"],
    "Pakistan": ["Netherlands Embassy Islamabad", "Netherlands Consulate Karachi"],
    "Nepal": ["Netherlands Embassy Kathmandu"],
    "Nigeria": ["Netherlands Embassy Abuja", "Netherlands Consulate-General Lagos"],
    "Ghana": ["Netherlands Embassy Accra"],
    "Kenya": ["Netherlands Embassy Nairobi"],
    "South Africa": ["Netherlands Embassy Pretoria"],
    "Egypt": ["Netherlands Embassy Cairo"],
    "Morocco": ["Netherlands Embassy Rabat"],
    "China": ["Netherlands Embassy Beijing", "Netherlands Consulate-General Shanghai", "Netherlands Consulate-General Guangzhou", "Netherlands Consulate-General Chengdu"],
    "Japan": ["Netherlands Embassy Tokyo"],
    "South Korea": ["Netherlands Embassy Seoul"],
    "Philippines": ["Netherlands Embassy Manila"],
    "Vietnam": ["Netherlands Embassy Hanoi", "Netherlands Consulate-General Ho Chi Minh City"],
    "Thailand": ["Netherlands Embassy Bangkok"],
    "Indonesia": ["Netherlands Embassy Jakarta"],
    "Malaysia": ["Netherlands Embassy Kuala Lumpur"],
    "Singapore": ["Netherlands Embassy Singapore"],
    "Turkey": ["Netherlands Embassy Ankara", "Netherlands Consulate-General Istanbul"],
    "Saudi Arabia": ["Netherlands Embassy Riyadh"],
    "United Arab Emirates": ["Netherlands Embassy Abu Dhabi"],
    "Brazil": ["Netherlands Embassy Brasilia", "Netherlands Consulate-General Sao Paulo", "Netherlands Consulate-General Rio de Janeiro"],
    "United States": ["Netherlands Embassy Washington D.C.", "Netherlands Consulate-General New York"],
    "United Kingdom": ["Netherlands Embassy London"],
    "Canada": ["Netherlands Embassy Ottawa", "Netherlands Consulate-General Toronto"],
    "Australia": ["Netherlands Embassy Canberra", "Netherlands Consulate-General Sydney"],
  },
  "Sweden": {
    "Bangladesh": ["Swedish Embassy Dhaka"],
    "India": ["Swedish Embassy New Delhi", "Swedish Consulate-General Mumbai"],
    "Pakistan": ["Swedish Embassy Islamabad"],
    "Nepal": ["Swedish Embassy Kathmandu"],
    "Nigeria": ["Swedish Embassy Abuja"],
    "Ghana": ["Swedish Embassy Accra"],
    "Kenya": ["Swedish Embassy Nairobi"],
    "South Africa": ["Swedish Embassy Pretoria"],
    "Egypt": ["Swedish Embassy Cairo"],
    "China": ["Swedish Embassy Beijing", "Swedish Consulate-General Shanghai", "Swedish Consulate-General Guangzhou"],
    "Japan": ["Swedish Embassy Tokyo"],
    "South Korea": ["Swedish Embassy Seoul"],
    "Philippines": ["Swedish Embassy Manila"],
    "Vietnam": ["Swedish Embassy Hanoi"],
    "Thailand": ["Swedish Embassy Bangkok"],
    "Indonesia": ["Swedish Embassy Jakarta"],
    "Malaysia": ["Swedish Embassy Kuala Lumpur"],
    "Singapore": ["Swedish Embassy Singapore"],
    "Turkey": ["Swedish Embassy Ankara", "Swedish Consulate-General Istanbul"],
    "United States": ["Swedish Embassy Washington D.C.", "Swedish Consulate-General New York", "Swedish Consulate-General Los Angeles"],
    "United Kingdom": ["Swedish Embassy London"],
    "Canada": ["Swedish Embassy Ottawa"],
    "Australia": ["Swedish Embassy Canberra"],
    "Saudi Arabia": ["Swedish Embassy Riyadh"],
    "United Arab Emirates": ["Swedish Embassy Abu Dhabi"],
  },
  "Denmark": {
    "Bangladesh": ["Danish Embassy Dhaka"],
    "India": ["Danish Embassy New Delhi", "Danish Consulate-General Mumbai"],
    "Pakistan": ["Danish Embassy Islamabad"],
    "Nepal": ["Danish Embassy Kathmandu"],
    "Nigeria": ["Danish Embassy Abuja"],
    "Kenya": ["Danish Embassy Nairobi"],
    "South Africa": ["Danish Embassy Pretoria"],
    "Egypt": ["Danish Embassy Cairo"],
    "China": ["Danish Embassy Beijing", "Danish Consulate-General Shanghai"],
    "Japan": ["Danish Embassy Tokyo"],
    "South Korea": ["Danish Embassy Seoul"],
    "Vietnam": ["Danish Embassy Hanoi"],
    "Thailand": ["Danish Embassy Bangkok"],
    "Indonesia": ["Danish Embassy Jakarta"],
    "Malaysia": ["Danish Embassy Kuala Lumpur"],
    "Singapore": ["Danish Embassy Singapore"],
    "Turkey": ["Danish Embassy Ankara", "Danish Consulate-General Istanbul"],
    "United States": ["Danish Embassy Washington D.C.", "Danish Consulate-General New York", "Danish Consulate-General Los Angeles"],
    "United Kingdom": ["Danish Embassy London"],
    "Canada": ["Danish Embassy Ottawa"],
    "Australia": ["Danish Embassy Canberra"],
  },
  "Norway": {
    "Bangladesh": ["Norwegian Embassy Dhaka"],
    "India": ["Norwegian Embassy New Delhi", "Norwegian Consulate-General Mumbai"],
    "Pakistan": ["Norwegian Embassy Islamabad"],
    "Nepal": ["Norwegian Embassy Kathmandu"],
    "Nigeria": ["Norwegian Embassy Abuja"],
    "Kenya": ["Norwegian Embassy Nairobi"],
    "Egypt": ["Norwegian Embassy Cairo"],
    "China": ["Norwegian Embassy Beijing", "Norwegian Consulate-General Shanghai"],
    "Japan": ["Norwegian Embassy Tokyo"],
    "South Korea": ["Norwegian Embassy Seoul"],
    "Philippines": ["Norwegian Embassy Manila"],
    "Vietnam": ["Norwegian Embassy Hanoi"],
    "Thailand": ["Norwegian Embassy Bangkok"],
    "Indonesia": ["Norwegian Embassy Jakarta"],
    "Malaysia": ["Norwegian Embassy Kuala Lumpur"],
    "Singapore": ["Norwegian Embassy Singapore"],
    "Turkey": ["Norwegian Embassy Ankara", "Norwegian Consulate-General Istanbul"],
    "United States": ["Norwegian Embassy Washington D.C.", "Norwegian Consulate-General New York", "Norwegian Consulate-General San Francisco", "Norwegian Consulate-General Minneapolis", "Norwegian Consulate-General Houston"],
    "United Kingdom": ["Norwegian Embassy London"],
    "Canada": ["Norwegian Embassy Ottawa"],
    "Australia": ["Norwegian Embassy Canberra"],
  },
  "Finland": {
    "Bangladesh": ["Finnish Embassy Dhaka"],
    "India": ["Finnish Embassy New Delhi"],
    "Pakistan": ["Finnish Embassy Islamabad"],
    "Nepal": ["Finnish Embassy Kathmandu"],
    "Nigeria": ["Finnish Embassy Abuja"],
    "Kenya": ["Finnish Embassy Nairobi"],
    "China": ["Finnish Embassy Beijing", "Finnish Consulate-General Shanghai"],
    "Japan": ["Finnish Embassy Tokyo"],
    "South Korea": ["Finnish Embassy Seoul"],
    "Vietnam": ["Finnish Embassy Hanoi"],
    "Thailand": ["Finnish Embassy Bangkok"],
    "Philippines": ["Finnish Embassy Manila"],
    "Indonesia": ["Finnish Embassy Jakarta"],
    "Malaysia": ["Finnish Embassy Kuala Lumpur"],
    "Singapore": ["Finnish Embassy Singapore"],
    "Turkey": ["Finnish Embassy Ankara", "Finnish Consulate-General Istanbul"],
    "United States": ["Finnish Embassy Washington D.C.", "Finnish Consulate-General New York", "Finnish Consulate-General Los Angeles"],
    "United Kingdom": ["Finnish Embassy London"],
    "Canada": ["Finnish Embassy Ottawa"],
    "Russia": ["Finnish Embassy Moscow", "Finnish Consulate-General St. Petersburg", "Finnish Consulate-General Petrozavodsk", "Finnish Consulate-General Murmansk"],
  },
  "Switzerland": {
    "Bangladesh": ["Swiss Embassy Dhaka"],
    "India": ["Swiss Embassy New Delhi", "Swiss Consulate-General Mumbai", "Swiss Consulate-General Bangalore"],
    "Pakistan": ["Swiss Embassy Islamabad", "Swiss Consulate-General Karachi"],
    "Nepal": ["Swiss Embassy Kathmandu"],
    "Sri Lanka": ["Swiss Embassy Colombo"],
    "Nigeria": ["Swiss Embassy Abuja"],
    "Ghana": ["Swiss Embassy Accra"],
    "Kenya": ["Swiss Embassy Nairobi"],
    "South Africa": ["Swiss Embassy Pretoria"],
    "Egypt": ["Swiss Embassy Cairo"],
    "Morocco": ["Swiss Embassy Rabat"],
    "China": ["Swiss Embassy Beijing", "Swiss Consulate-General Shanghai", "Swiss Consulate-General Guangzhou", "Swiss Consulate-General Chengdu"],
    "Japan": ["Swiss Embassy Tokyo", "Swiss Consulate-General Osaka"],
    "South Korea": ["Swiss Embassy Seoul"],
    "Philippines": ["Swiss Embassy Manila"],
    "Vietnam": ["Swiss Embassy Hanoi"],
    "Thailand": ["Swiss Embassy Bangkok"],
    "Indonesia": ["Swiss Embassy Jakarta"],
    "Malaysia": ["Swiss Embassy Kuala Lumpur"],
    "Singapore": ["Swiss Embassy Singapore"],
    "Turkey": ["Swiss Embassy Ankara", "Swiss Consulate-General Istanbul"],
    "United States": ["Swiss Embassy Washington D.C.", "Swiss Consulate-General New York", "Swiss Consulate-General San Francisco", "Swiss Consulate-General Los Angeles", "Swiss Consulate-General Chicago"],
    "United Kingdom": ["Swiss Embassy London"],
    "Canada": ["Swiss Embassy Ottawa"],
    "Australia": ["Swiss Embassy Canberra"],
    "Brazil": ["Swiss Embassy Brasilia", "Swiss Consulate-General Sao Paulo"],
    "Saudi Arabia": ["Swiss Embassy Riyadh"],
    "United Arab Emirates": ["Swiss Embassy Abu Dhabi", "Swiss Consulate-General Dubai"],
    "Iran": ["Swiss Embassy Tehran (also serves U.S. Protecting Power interests)"],
  },
  "Austria": {
    "Bangladesh": ["Austrian Embassy Dhaka"],
    "India": ["Austrian Embassy New Delhi", "Austrian Consulate-General Mumbai"],
    "Pakistan": ["Austrian Embassy Islamabad"],
    "Nepal": ["Austrian Embassy Kathmandu"],
    "Nigeria": ["Austrian Embassy Abuja"],
    "Egypt": ["Austrian Embassy Cairo"],
    "China": ["Austrian Embassy Beijing", "Austrian Consulate-General Shanghai"],
    "Japan": ["Austrian Embassy Tokyo"],
    "South Korea": ["Austrian Embassy Seoul"],
    "Vietnam": ["Austrian Embassy Hanoi"],
    "Thailand": ["Austrian Embassy Bangkok"],
    "Philippines": ["Austrian Embassy Manila"],
    "Indonesia": ["Austrian Embassy Jakarta"],
    "Malaysia": ["Austrian Embassy Kuala Lumpur"],
    "Singapore": ["Austrian Embassy Singapore"],
    "Turkey": ["Austrian Embassy Ankara", "Austrian Consulate-General Istanbul"],
    "United States": ["Austrian Embassy Washington D.C.", "Austrian Consulate-General New York", "Austrian Consulate-General Los Angeles", "Austrian Consulate-General Chicago"],
    "United Kingdom": ["Austrian Embassy London"],
    "Canada": ["Austrian Embassy Ottawa"],
    "Australia": ["Austrian Embassy Canberra"],
    "Russia": ["Austrian Embassy Moscow"],
    "Saudi Arabia": ["Austrian Embassy Riyadh"],
    "United Arab Emirates": ["Austrian Embassy Abu Dhabi"],
  },
  "Belgium": {
    "Bangladesh": ["Belgian Embassy Dhaka"],
    "India": ["Belgian Embassy New Delhi", "Belgian Consulate-General Mumbai"],
    "Pakistan": ["Belgian Embassy Islamabad"],
    "Nepal": ["Belgian Embassy Kathmandu"],
    "Nigeria": ["Belgian Embassy Abuja", "Belgian Consulate-General Lagos"],
    "Ghana": ["Belgian Embassy Accra"],
    "Kenya": ["Belgian Embassy Nairobi"],
    "Egypt": ["Belgian Embassy Cairo"],
    "Morocco": ["Belgian Embassy Rabat", "Belgian Consulate-General Casablanca"],
    "China": ["Belgian Embassy Beijing", "Belgian Consulate-General Shanghai", "Belgian Consulate-General Guangzhou"],
    "Japan": ["Belgian Embassy Tokyo"],
    "South Korea": ["Belgian Embassy Seoul"],
    "Vietnam": ["Belgian Embassy Hanoi"],
    "Thailand": ["Belgian Embassy Bangkok"],
    "Philippines": ["Belgian Embassy Manila"],
    "Indonesia": ["Belgian Embassy Jakarta"],
    "Malaysia": ["Belgian Embassy Kuala Lumpur"],
    "Singapore": ["Belgian Embassy Singapore"],
    "Turkey": ["Belgian Embassy Ankara", "Belgian Consulate-General Istanbul"],
    "United States": ["Belgian Embassy Washington D.C.", "Belgian Consulate-General New York", "Belgian Consulate-General Los Angeles"],
    "United Kingdom": ["Belgian Embassy London"],
    "Canada": ["Belgian Embassy Ottawa"],
    "Australia": ["Belgian Embassy Canberra"],
    "Saudi Arabia": ["Belgian Embassy Riyadh"],
    "United Arab Emirates": ["Belgian Embassy Abu Dhabi"],
  },
  "Ireland": {
    "Bangladesh": ["Irish Embassy Dhaka"],
    "India": ["Irish Embassy New Delhi", "Irish Consulate-General Mumbai"],
    "Pakistan": ["Irish Embassy Islamabad"],
    "Nigeria": ["Irish Embassy Abuja", "Irish Consulate-General Lagos"],
    "South Africa": ["Irish Embassy Pretoria"],
    "Kenya": ["Irish Embassy Nairobi"],
    "Egypt": ["Irish Embassy Cairo"],
    "China": ["Irish Embassy Beijing", "Irish Consulate-General Shanghai"],
    "Japan": ["Irish Embassy Tokyo"],
    "South Korea": ["Irish Embassy Seoul"],
    "Vietnam": ["Irish Embassy Hanoi"],
    "Thailand": ["Irish Embassy Bangkok"],
    "Philippines": ["Irish Embassy Manila"],
    "Indonesia": ["Irish Embassy Jakarta"],
    "Malaysia": ["Irish Embassy Kuala Lumpur"],
    "Singapore": ["Irish Embassy Singapore"],
    "United States": ["Irish Embassy Washington D.C.", "Irish Consulate-General New York", "Irish Consulate-General Boston", "Irish Consulate-General Chicago", "Irish Consulate-General San Francisco"],
    "United Kingdom": ["Irish Embassy London", "Irish Consulate-General Edinburgh"],
    "Canada": ["Irish Embassy Ottawa", "Irish Consulate-General Toronto", "Irish Consulate-General Vancouver"],
    "Australia": ["Irish Embassy Canberra", "Irish Consulate-General Sydney", "Irish Consulate-General Melbourne"],
    "Saudi Arabia": ["Irish Embassy Riyadh"],
    "United Arab Emirates": ["Irish Embassy Abu Dhabi"],
  },
  "Schengen Area (Europe)": {
    "Bangladesh": ["German Embassy Dhaka", "French Embassy Dhaka", "Italian Embassy Dhaka", "Spanish Embassy Dhaka", "Netherlands Embassy Dhaka"],
    "India": ["German Embassy New Delhi", "French Embassy New Delhi", "Italian Embassy New Delhi", "Spanish Embassy New Delhi", "Netherlands Embassy New Delhi"],
    "Pakistan": ["German Embassy Islamabad", "French Embassy Islamabad", "Italian Embassy Islamabad", "Netherlands Embassy Islamabad"],
    "Nepal": ["German Embassy Kathmandu", "French Embassy Kathmandu", "Italian Embassy Kathmandu"],
    "Nigeria": ["German Embassy Abuja", "French Embassy Abuja", "Italian Embassy Abuja"],
    "China": ["German Embassy Beijing", "French Embassy Beijing", "Spanish Embassy Beijing"],
    "Japan": ["German Embassy Tokyo", "French Embassy Tokyo", "Italian Embassy Tokyo"],
    "South Korea": ["German Embassy Seoul", "French Embassy Seoul", "Italian Embassy Seoul"],
    "Philippines": ["German Embassy Manila", "French Embassy Manila", "Spanish Embassy Manila"],
    "Vietnam": ["German Embassy Hanoi", "French Embassy Hanoi"],
    "Thailand": ["German Embassy Bangkok", "French Embassy Bangkok"],
    "Indonesia": ["German Embassy Jakarta", "French Embassy Jakarta"],
    "Malaysia": ["German Embassy Kuala Lumpur", "French Embassy Kuala Lumpur"],
    "Singapore": ["German Embassy Singapore", "French Embassy Singapore"],
    "Turkey": ["German Embassy Ankara", "French Embassy Ankara", "Italian Embassy Ankara"],
    "United States": ["German Embassy Washington D.C.", "French Embassy Washington D.C.", "Italian Embassy Washington D.C."],
    "United Kingdom": ["German Embassy London", "French Embassy London", "Italian Embassy London"],
    "Canada": ["German Embassy Ottawa", "French Embassy Ottawa", "Italian Embassy Ottawa"],
    "Australia": ["German Embassy Canberra", "French Embassy Canberra", "Italian Embassy Canberra"],
    "Brazil": ["German Embassy Brasilia", "French Embassy Brasilia", "Italian Embassy Brasilia"],
    "Morocco": ["French Embassy Rabat", "Spanish Embassy Rabat", "German Embassy Rabat"],
    "Saudi Arabia": ["German Embassy Riyadh", "French Embassy Riyadh", "Italian Embassy Riyadh"],
    "United Arab Emirates": ["German Embassy Abu Dhabi", "French Embassy Abu Dhabi", "Italian Embassy Abu Dhabi"],
  },
  "New Zealand": {
    "Bangladesh": ["New Zealand High Commission Dhaka"],
    "India": ["New Zealand High Commission New Delhi", "New Zealand Consulate-General Mumbai"],
    "Pakistan": ["New Zealand High Commission Islamabad"],
    "Nepal": ["New Zealand Embassy Kathmandu"],
    "Sri Lanka": ["New Zealand High Commission Colombo"],
    "Nigeria": ["New Zealand High Commission Abuja"],
    "South Africa": ["New Zealand High Commission Pretoria"],
    "Kenya": ["New Zealand High Commission Nairobi"],
    "China": ["New Zealand Embassy Beijing", "New Zealand Consulate-General Shanghai", "New Zealand Consulate-General Guangzhou"],
    "Japan": ["New Zealand Embassy Tokyo"],
    "South Korea": ["New Zealand Embassy Seoul"],
    "Philippines": ["New Zealand Embassy Manila"],
    "Vietnam": ["New Zealand Embassy Hanoi", "New Zealand Consulate-General Ho Chi Minh City"],
    "Thailand": ["New Zealand Embassy Bangkok"],
    "Indonesia": ["New Zealand Embassy Jakarta"],
    "Malaysia": ["New Zealand High Commission Kuala Lumpur"],
    "Singapore": ["New Zealand High Commission Singapore"],
    "United States": ["New Zealand Embassy Washington D.C.", "New Zealand Consulate-General New York", "New Zealand Consulate-General Los Angeles", "New Zealand Consulate-General San Francisco"],
    "United Kingdom": ["New Zealand High Commission London"],
    "Canada": ["New Zealand High Commission Ottawa", "New Zealand Consulate-General Vancouver"],
    "Australia": ["New Zealand High Commission Canberra", "New Zealand Consulate-General Sydney", "New Zealand Consulate-General Melbourne", "New Zealand Consulate-General Brisbane"],
    "Germany": ["New Zealand Embassy Berlin"],
    "France": ["New Zealand Embassy Paris"],
    "Saudi Arabia": ["New Zealand Embassy Riyadh"],
    "United Arab Emirates": ["New Zealand Embassy Abu Dhabi"],
  },
  "Japan": {
    "Bangladesh": ["Embassy of Japan Dhaka"],
    "India": ["Embassy of Japan New Delhi", "Consulate-General of Japan Mumbai", "Consulate-General of Japan Chennai", "Consulate-General of Japan Kolkata", "Consulate-General of Japan Bangalore"],
    "Pakistan": ["Embassy of Japan Islamabad", "Consulate-General of Japan Karachi"],
    "Nepal": ["Embassy of Japan Kathmandu"],
    "Sri Lanka": ["Embassy of Japan Colombo"],
    "Nigeria": ["Embassy of Japan Abuja", "Consulate-General of Japan Lagos"],
    "Ghana": ["Embassy of Japan Accra"],
    "Kenya": ["Embassy of Japan Nairobi"],
    "South Africa": ["Embassy of Japan Pretoria"],
    "Egypt": ["Embassy of Japan Cairo"],
    "China": ["Embassy of Japan Beijing", "Consulate-General of Japan Shanghai", "Consulate-General of Japan Guangzhou", "Consulate-General of Japan Chongqing", "Consulate-General of Japan Shenyang", "Consulate-General of Japan Chengdu"],
    "South Korea": ["Embassy of Japan Seoul", "Consulate-General of Japan Busan", "Consulate-General of Japan Jeju"],
    "Philippines": ["Embassy of Japan Manila", "Consulate-General of Japan Cebu"],
    "Vietnam": ["Embassy of Japan Hanoi", "Consulate-General of Japan Ho Chi Minh City", "Consulate-General of Japan Da Nang"],
    "Thailand": ["Embassy of Japan Bangkok"],
    "Indonesia": ["Embassy of Japan Jakarta"],
    "Malaysia": ["Embassy of Japan Kuala Lumpur"],
    "Singapore": ["Embassy of Japan Singapore"],
    "Myanmar": ["Embassy of Japan Yangon"],
    "Cambodia": ["Embassy of Japan Phnom Penh"],
    "Turkey": ["Embassy of Japan Ankara", "Consulate-General of Japan Istanbul"],
    "Iran": ["Embassy of Japan Tehran"],
    "United States": ["Embassy of Japan Washington D.C.", "Consulate-General of Japan New York", "Consulate-General of Japan Los Angeles", "Consulate-General of Japan San Francisco", "Consulate-General of Japan Chicago", "Consulate-General of Japan Houston", "Consulate-General of Japan Honolulu"],
    "United Kingdom": ["Embassy of Japan London"],
    "Canada": ["Embassy of Japan Ottawa", "Consulate-General of Japan Toronto", "Consulate-General of Japan Vancouver", "Consulate-General of Japan Calgary", "Consulate-General of Japan Montreal"],
    "Australia": ["Embassy of Japan Canberra", "Consulate-General of Japan Sydney", "Consulate-General of Japan Melbourne", "Consulate-General of Japan Brisbane", "Consulate-General of Japan Perth"],
    "Brazil": ["Embassy of Japan Brasilia", "Consulate-General of Japan Sao Paulo", "Consulate-General of Japan Curitiba"],
    "Germany": ["Embassy of Japan Berlin", "Consulate-General of Japan Hamburg", "Consulate-General of Japan Frankfurt", "Consulate-General of Japan Munich"],
    "France": ["Embassy of Japan Paris"],
    "Saudi Arabia": ["Embassy of Japan Riyadh", "Consulate-General of Japan Jeddah"],
    "United Arab Emirates": ["Embassy of Japan Abu Dhabi", "Consulate-General of Japan Dubai"],
    "Russia": ["Embassy of Japan Moscow", "Consulate-General of Japan Vladivostok", "Consulate-General of Japan Sakhalin"],
    "Kazakhstan": ["Embassy of Japan Nur-Sultan"],
    "Uzbekistan": ["Embassy of Japan Tashkent"],
    "Ethiopia": ["Embassy of Japan Addis Ababa"],
  },
  "Singapore": {
    "Bangladesh": ["Singapore High Commission Dhaka"],
    "India": ["Singapore High Commission New Delhi", "Singapore Consulate-General Mumbai", "Singapore Consulate-General Chennai"],
    "Pakistan": ["Singapore High Commission Islamabad", "Singapore Consulate-General Karachi"],
    "Nepal": ["Singapore Embassy Kathmandu"],
    "Sri Lanka": ["Singapore High Commission Colombo"],
    "China": ["Singapore Embassy Beijing", "Singapore Consulate-General Shanghai", "Singapore Consulate-General Guangzhou", "Singapore Consulate-General Chengdu", "Singapore Consulate-General Xiamen"],
    "Japan": ["Singapore Embassy Tokyo", "Singapore Consulate-General Osaka"],
    "South Korea": ["Singapore Embassy Seoul"],
    "Philippines": ["Singapore Embassy Manila"],
    "Vietnam": ["Singapore Embassy Hanoi", "Singapore Consulate-General Ho Chi Minh City"],
    "Thailand": ["Singapore Embassy Bangkok"],
    "Indonesia": ["Singapore Embassy Jakarta", "Singapore Consulate-General Batam"],
    "Malaysia": ["Singapore High Commission Kuala Lumpur", "Singapore Consulate-General Johor Bahru"],
    "Myanmar": ["Singapore Embassy Yangon"],
    "United States": ["Singapore Embassy Washington D.C.", "Singapore Consulate-General New York", "Singapore Consulate-General Los Angeles", "Singapore Consulate-General San Francisco", "Singapore Consulate-General Chicago", "Singapore Consulate-General Houston"],
    "United Kingdom": ["Singapore High Commission London"],
    "Canada": ["Singapore High Commission Ottawa", "Singapore Consulate-General Toronto", "Singapore Consulate-General Vancouver"],
    "Australia": ["Singapore High Commission Canberra", "Singapore Consulate-General Sydney", "Singapore Consulate-General Melbourne", "Singapore Consulate-General Perth"],
    "Germany": ["Singapore Embassy Berlin"],
    "France": ["Singapore Embassy Paris"],
    "Saudi Arabia": ["Singapore Embassy Riyadh"],
    "United Arab Emirates": ["Singapore Embassy Abu Dhabi", "Singapore Consulate-General Dubai"],
  },
  "South Korea": {
    "Bangladesh": ["Korean Embassy Dhaka"],
    "India": ["Korean Embassy New Delhi", "Korean Consulate-General Mumbai", "Korean Consulate-General Chennai", "Korean Consulate-General Kolkata"],
    "Pakistan": ["Korean Embassy Islamabad", "Korean Consulate-General Karachi"],
    "Nepal": ["Korean Embassy Kathmandu"],
    "Sri Lanka": ["Korean Embassy Colombo"],
    "Nigeria": ["Korean Embassy Abuja"],
    "Ghana": ["Korean Embassy Accra"],
    "Kenya": ["Korean Embassy Nairobi"],
    "Ethiopia": ["Korean Embassy Addis Ababa"],
    "Egypt": ["Korean Embassy Cairo"],
    "China": ["Korean Embassy Beijing", "Korean Consulate-General Shanghai", "Korean Consulate-General Guangzhou", "Korean Consulate-General Qingdao", "Korean Consulate-General Shenyang", "Korean Consulate-General Chengdu", "Korean Consulate-General Wuhan"],
    "Japan": ["Korean Embassy Tokyo", "Korean Consulate-General Osaka", "Korean Consulate-General Fukuoka", "Korean Consulate-General Nagoya", "Korean Consulate-General Sapporo", "Korean Consulate-General Hiroshima"],
    "Philippines": ["Korean Embassy Manila", "Korean Consulate-General Cebu"],
    "Vietnam": ["Korean Embassy Hanoi", "Korean Consulate-General Ho Chi Minh City", "Korean Consulate-General Da Nang"],
    "Thailand": ["Korean Embassy Bangkok"],
    "Indonesia": ["Korean Embassy Jakarta"],
    "Malaysia": ["Korean Embassy Kuala Lumpur"],
    "Singapore": ["Korean Embassy Singapore"],
    "Myanmar": ["Korean Embassy Yangon"],
    "Cambodia": ["Korean Embassy Phnom Penh"],
    "United States": ["Korean Embassy Washington D.C.", "Korean Consulate-General New York", "Korean Consulate-General Los Angeles", "Korean Consulate-General San Francisco", "Korean Consulate-General Chicago", "Korean Consulate-General Seattle", "Korean Consulate-General Boston", "Korean Consulate-General Honolulu", "Korean Consulate-General Houston", "Korean Consulate-General Atlanta"],
    "United Kingdom": ["Korean Embassy London"],
    "Canada": ["Korean Embassy Ottawa", "Korean Consulate-General Toronto", "Korean Consulate-General Vancouver"],
    "Australia": ["Korean Embassy Canberra", "Korean Consulate-General Sydney", "Korean Consulate-General Melbourne", "Korean Consulate-General Brisbane"],
    "Germany": ["Korean Embassy Berlin", "Korean Consulate-General Frankfurt", "Korean Consulate-General Hamburg"],
    "France": ["Korean Embassy Paris"],
    "Russia": ["Korean Embassy Moscow", "Korean Consulate-General Vladivostok", "Korean Consulate-General St. Petersburg"],
    "Saudi Arabia": ["Korean Embassy Riyadh", "Korean Consulate-General Jeddah"],
    "United Arab Emirates": ["Korean Embassy Abu Dhabi", "Korean Consulate-General Dubai"],
    "Kazakhstan": ["Korean Embassy Nur-Sultan", "Korean Consulate-General Almaty"],
    "Uzbekistan": ["Korean Embassy Tashkent"],
    "Brazil": ["Korean Embassy Brasilia", "Korean Consulate-General Sao Paulo"],
    "Mexico": ["Korean Embassy Mexico City"],
  },
}
